### ISSUE TITLE
3a4 inhibition ckpt is missing

### ISSUE THREAD

**Issue by orgw** [datagrok-ai/admetica#11]
Hi 

3a4 inhibition ckpt is missing

seems to be missing

the following ckpts existing are

Caco2.ckpt    CL-Micro.ckpt          CYP1A2-Substrate.ckpt   CYP2C19-Substrate.ckpt  CYP2C9-Substrate.ckpt  CYP2D6-Substrate.ckpt  hERG.ckpt  Lipophilicity.ckpt  Solubility.ckpt
CL-Hepa.ckpt  CYP1A2-Inhibitor.ckpt  CYP2C19-Inhibitor.ckpt  CYP2C9-Inhibitor.ckpt   CYP2D6-Inhibitor.ckpt  Half-Life.ckpt         LD50.ckpt  PPBR.ckpt           VDss.ckpt

**Comment by orgw** [comment]
raise ValueError(f"No matching model file found for model '{model_name}'")
ValueError: No matching model file found for model 'CYP3A4-Inhibitor'

**Comment by Aleksashka11** [comment]
Hi! I've already added the missing model to the repository.
Will update the models in the library itself and get you know!

**Comment by Aleksashka11** [comment]
I've already published a new admetica version (1.4.1) that contains cyp3a4-inhibitor model.
Hope that will help you!

**Comment by orgw** [comment]
thanks working perfectly, will there be a training code for a custom dataset? or is it the same process as training a chemprop model?

**Comment by Aleksashka11** [comment]
Yes, it is essentially the same as training a chemprop model. For more details, you can refer to the chemprop [documentation](https://github.com/chemprop/chemprop/blob/master/README.md#training), linked in our README.
